// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMSuR4lBNCuhfBSXyx7ZDWoTZJeWeaDk',
    appId: '1:627094072428:web:ba442a700e30790b5a7c49',
    messagingSenderId: '627094072428',
    projectId: 'food-pharmer',
    authDomain: 'food-pharmer.firebaseapp.com',
    storageBucket: 'food-pharmer.firebasestorage.app',
    measurementId: 'G-THYTJQQTYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWMSae8bssvsb88HK1Ji1QgigiOVWtQQ',
    appId: '1:627094072428:android:28023ef5e247ee1c5a7c49',
    messagingSenderId: '627094072428',
    projectId: 'food-pharmer',
    storageBucket: 'food-pharmer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfCO5tSdKa2vqwHhhY-S7TQAl4QEaoZhI',
    appId: '1:627094072428:ios:b44526e7f20139f35a7c49',
    messagingSenderId: '627094072428',
    projectId: 'food-pharmer',
    storageBucket: 'food-pharmer.firebasestorage.app',
    iosClientId: '627094072428-gv3jqt3dsdgsoj5l6smp1p6trbp03elq.apps.googleusercontent.com',
    iosBundleId: 'com.jenu.foodpharmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfCO5tSdKa2vqwHhhY-S7TQAl4QEaoZhI',
    appId: '1:627094072428:ios:b44526e7f20139f35a7c49',
    messagingSenderId: '627094072428',
    projectId: 'food-pharmer',
    storageBucket: 'food-pharmer.firebasestorage.app',
    iosClientId: '627094072428-gv3jqt3dsdgsoj5l6smp1p6trbp03elq.apps.googleusercontent.com',
    iosBundleId: 'com.jenu.foodpharmer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSMSuR4lBNCuhfBSXyx7ZDWoTZJeWeaDk',
    appId: '1:627094072428:web:e13908d43670b4a75a7c49',
    messagingSenderId: '627094072428',
    projectId: 'food-pharmer',
    authDomain: 'food-pharmer.firebaseapp.com',
    storageBucket: 'food-pharmer.firebasestorage.app',
    measurementId: 'G-YLH7MJ33N5',
  );
}
